session_name: Dotfiles
start_directory: ~/.dotfiles
windows:
  - window_name: .dotfiles
    panes:
      - shell_command:
          - cmd: "clear"
          - cmd: "nvim"
  - window_name: AstroNvim
    start_directory: "~/.local/share/nvim/lazy/AstroNvim/"
    panes:
      - shell_command:
          - cmd: "clear"
  - window_name: AstroCore
    start_directory: "~/.local/share/nvim/lazy/astrocore"
    panes:
      - shell_command:
          - cmd: "clear"
  - window_name: AstroLSP
    start_directory: "~/.local/share/nvim/lazy/astrolsp"
    panes:
      - shell_command:
          - cmd: "clear"
  - window_name: AstroUi
    start_directory: "~/.local/share/nvim/lazy/astroui"
    panes:
      - shell_command:
          - cmd: "clear"
  - window_name: Plugins
    start_directory: "~/.local/share/nvim/lazy"
    panes:
      - shell_command:
          - cmd: "clear"
